version: '3'
services:
  db:
    image: mysql:5
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    networks:
      - todo_sec
  web:
    tty: true
    stdin_open: true
    image: saghaulor/todo_security:latest
    environment:
      RAILS_ENV: production
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    networks:
      - todo_sec
    depends_on:
      - db

networks:
  todo_sec:
    driver: bridge